#lang racket
(require ffi/unsafe)
(define-cstruct _Vector2 ([x _float]
                          [y _float]
                          ))
(define-cstruct _Vector3 ([x _float]
                          [y _float]
                          [z _float]
                          ))
(define-cstruct _Vector4 ([x _float]
                          [y _float]
                          [z _float]
                          [w _float]
                          ))
(define-cstruct _Matrix ([m0 _float]
                         [m4 _float]
                         [m8 _float]
                         [m12 _float]
                         [m1 _float]
                         [m5 _float]
                         [m9 _float]
                         [m13 _float]
                         [m2 _float]
                         [m6 _float]
                         [m10 _float]
                         [m14 _float]
                         [m3 _float]
                         [m7 _float]
                         [m11 _float]
                         [m15 _float]
                         ))
(define-cstruct _Color ([r _ubyte]
                        [g _ubyte]
                        [b _ubyte]
                        [a _ubyte]
                        ))
(define-cstruct _Rectangle ([x _float]
                            [y _float]
                            [width _float]
                            [height _float]
                            ))
(define-cstruct _Image ([*data _void]
                        [width _int]
                        [height _int]
                        [mipmaps _int]
                        [format _int]
                        ))
(define-cstruct _Texture ([id _uint]
                          [width _int]
                          [height _int]
                          [mipmaps _int]
                          [format _int]
                          ))
(define-cstruct _RenderTexture ([id _uint]
                                [texture _Texture]
                                [depth _Texture]
                                ))
(define-cstruct _NPatchInfo ([source _Rectangle]
                             [left _int]
                             [top _int]
                             [right _int]
                             [bottom _int]
                             [layout _int]
                             ))
(define-cstruct _GlyphInfo ([value _int]
                            [offsetX _int]
                            [offsetY _int]
                            [advanceX _int]
                            [image _Image]
                            ))
(define-cstruct _Font ([baseSize _int]
                       [glyphCount _int]
                       [glyphPadding _int]
                       [texture _Texture2D]
                       [*recs _Rectangle]
                       [*glyphs _GlyphInfo]
                       ))
(define-cstruct _Camera3D ([position _Vector3]
                           [target _Vector3]
                           [up _Vector3]
                           [fovy _float]
                           [projection _int]
                           ))
(define-cstruct _Camera2D ([offset _Vector2]
                           [target _Vector2]
                           [rotation _float]
                           [zoom _float]
                           ))
(define-cstruct _Mesh ([vertexCount _int]
                       [triangleCount _int]
                       [*vertices _float]
                       [*texcoords _float]
                       [*texcoords2 _float]
                       [*normals _float]
                       [*tangents _float]
                       [*colors _ubyte]
                       [*indices _ushort]
                       [*animVertices _float]
                       [*animNormals _float]
                       [*boneIds _ubyte]
                       [*boneWeights _float]
                       [vaoId _uint]
                       [*vboId _uint]
                       ))
(define-cstruct _Shader ([id _uint]
                         [*locs _int]
                         ))
(define-cstruct _MaterialMap ([texture _Texture2D]
                              [color _Color]
                              [value _float]
                              ))
(define-cstruct _Material ([shader _Shader]
                           [*maps _MaterialMap]
                           [params[4] _float]
                           ))
(define-cstruct _Transform ([translation _Vector3]
                            [rotation _Quaternion]
                            [scale _Vector3]
                            ))
(define-cstruct _BoneInfo ([name[32] _sbyte]
                           [parent _int]
                           ))
(define-cstruct _Model ([transform _Matrix]
                        [meshCount _int]
                        [materialCount _int]
                        [*meshes _Mesh]
                        [*materials _Material]
                        [*meshMaterial _int]
                        [boneCount _int]
                        [*bones _BoneInfo]
                        [*bindPose _Transform]
                        ))
(define-cstruct _ModelAnimation ([boneCount _int]
                                 [frameCount _int]
                                 [*bones _BoneInfo]
                                 [**framePoses _Transform]
                                 [name[32] _sbyte]
                                 ))
(define-cstruct _Ray ([position _Vector3]
                      [direction _Vector3]
                      ))
(define-cstruct _RayCollision ([hit _stdbool]
                               [distance _float]
                               [point _Vector3]
                               [normal _Vector3]
                               ))
(define-cstruct _BoundingBox ([min _Vector3]
                              [max _Vector3]
                              ))
(define-cstruct _Wave ([frameCount _uint]
                       [sampleRate _uint]
                       [sampleSize _uint]
                       [channels _uint]
                       [*data _void]
                       ))
(define-cstruct _AudioStream ([*buffer _rAudioBuffer]
                              [*processor _rAudioProcessor]
                              [sampleRate _uint]
                              [sampleSize _uint]
                              [channels _uint]
                              ))
(define-cstruct _Sound ([stream _AudioStream]
                        [frameCount _uint]
                        ))
(define-cstruct _Music ([stream _AudioStream]
                        [frameCount _uint]
                        [looping _stdbool]
                        [ctxType _int]
                        [*ctxData _void]
                        ))
(define-cstruct _VrDeviceInfo ([hResolution _int]
                               [vResolution _int]
                               [hScreenSize _float]
                               [vScreenSize _float]
                               [vScreenCenter _float]
                               [eyeToScreenDistance _float]
                               [lensSeparationDistance _float]
                               [interpupillaryDistance _float]
                               [lensDistortionValues[4] _float]
                               [chromaAbCorrection[4] _float]
                               ))
(define-cstruct _VrStereoConfig ([projection[2] _Matrix]
                                 [viewOffset[2] _Matrix]
                                 [leftLensCenter[2] _float]
                                 [rightLensCenter[2] _float]
                                 [leftScreenCenter[2] _float]
                                 [rightScreenCenter[2] _float]
                                 [scale[2] _float]
                                 [scaleIn[2] _float]
                                 ))
(define-cstruct _FilePathList ([capacity _uint]
                               [count _uint]
                               [**paths _sbyte]
                               ))
(define-cstruct _AutomationEvent ([frame _uint]
                                  [type _uint]
                                  [params[4] _int]
                                  ))
(define-cstruct _AutomationEventList ([capacity _uint]
                                      [count _uint]
                                      [*events _AutomationEvent]
                                      ))